### ISSUE TITLE
panel-primary和panel-info颜色一样

### ISSUE THREAD

**Issue by malichan** [ruiii/poi_theme_paper_dark#10]
感觉不太好呢……

**Comment by ruiii** [comment]
paper的info是基佬紫色，panel-primary的话好像没有panel-info用的多。
如果要用到info的话，是换个颜色比较好。
但是换什么色呢。。。

**Comment by hanzhao** [comment]
http://fezvrasta.github.io/bootstrap-material-design/#material-colors
