### ISSUE TITLE
资源的框的上下 margin 不对称

### ISSUE THREAD

**Issue by dkwingsmt** [ruiii/poi_theme_paper_dark#14]
这人说他忍了很久了，特别难受……
![image](https://cloud.githubusercontent.com/assets/1596656/11648045/3113fb6a-9d35-11e5-9b8a-65ed20d58a47.png)

**Comment by ruiii** [comment]
是指内边距吗？
看了下除了lumen系列的不明显以外 其他主题都有这个问题
所以应该是需要在面板那边修改一下css style

**Comment by dkwingsmt** [comment]
看来是
